dotlottie/player-component

- package.json
- src/dotlottie-player.ts
- src/index.html
v1.2.2 adds passing a rendererSettings object to the load method.
> feat: added renderer settings object to load method

- apps/react-player-test/src/pages/Test.tsx
- packages/common/src/dotlottie-player.ts
- packages/react-player/src/react-player.tsx
> feat: Added props intermission and count

- src/dotlottie-player.ts
- src/manifest.ts
- tests/index.html
- tests/without-tests.html
Completes: DOTL-104, DOTL-95
- async unzip method
- loop as string (boolean as string or number representing number of times to loop)
> feat: moved to async unzip method + loop as string

- packages/react-player/src/controls.tsx
- packages/react-player/src/hooks/use-dotlottie-player.ts
- packages/react-player/src/react-player.tsx
Fixed some lint issues. 
packages/react-player
> chore(react): fixed lint issues.

- packages/common/package.json
> chore: updated dotlottie-js

- .github/workflows/main.yml
- .npmrc
- packages/common/package.json
- packages/player-component/cypress/integration/lottie-player/load_animation.spec.js
- packages/react-player/package.json
- pnpm-lock.yaml
> fix: package versioning

- package.json
- src/dotlottie-player.ts
> fix: fixed encoded image check

- .changeset/soft-shrimps-carry.md
- packages/react-player/tsup.config.js
> fix: 🐛 dts issue fixed

- packages/react-player/cypress/component/props.cy.tsx
> test: 💍 fixed a test issue

- .changeset/lucky-lies-fly.md
- packages/common/src/dotlottie-player.ts
- packages/player-component/src/dotlottie-player.ts
> chore: 🤖 moved visibilitychange to common

- packages/common/src/dotlottie-player.ts
- packages/common/src/state/dotlottie-state-machine.ts
> fix: 🐛 the playbackoptions being passed on to next animation

- apps/player-component-web/src/loader.ts
- packages/common/src/dotlottie-player.ts
- packages/player-component/src/dotlottie-player.ts
- packages/react-player/src/hooks/use-dotlottie-player.ts
- packages/react-player/src/react-player.tsx
> feat: added enter interactive mode & restricted methods

- packages/common/src/dotlottie-player.ts
> feat: 🎸 added comments for readability and added complete state

- .changeset/twelve-lemons-relate.md
- apps/react-player-next/package.json
- packages/common/package.json
- packages/common/src/dotlottie-loader.ts
- packages/common/src/dotlottie-player.ts
- packages/common/src/utils.ts
- packages/player-component/src/dotlottie-player.ts
- pnpm-lock.yaml
> feat: 🎸 selective decompression of animations

- .changeset/fuzzy-vans-guess.md
- .github/workflows/main.yml
- packages/react-player/cypress/support/component.ts
- packages/react-player/package.json
- packages/react-player/src/hooks/use-dotlottie-state.ts
- packages/react-player/src/hooks/use-select-dotlottie-state.ts
- packages/react-player/src/hooks/use-sync-external-store.ts
- packages/react-player/src/index.ts
- pnpm-lock.yaml
> feat: 🎸 added react17 support

- .changeset/fuzzy-monkeys-warn.md
- packages/common/src/dotlottie-player.ts
- packages/react-player/src/controls.tsx
> fix: 🐛 double render on next() and previous()

- .github/workflows/main.yml
- packages/react-player/src/hooks/use-dotlottie-player.ts
- packages/react-player/src/hooks/use-effect-once.ts
> fix: 🐛 loading of DotLottiePlayer in react-player component

- .changeset/hungry-mails-wave.md
- packages/common/src/dotlottie-loader.ts
- packages/react-player/cypress/component/speed.cy.tsx
> fix: 🐛 content-type check for .json urls

- .changeset/clever-owls-run.md
- packages/react-player/src/react-player.tsx
> fix: set default value for className props to prevent undefined

- packages/player-component/cypress/component/get-versions.cy.ts
- packages/player-component/cypress/component/interactivity/enable-interactivity.cy.ts
- packages/player-component/cypress/component/interactivity/exploding-pigeon.cy.ts
- packages/player-component/cypress/component/interactivity/state-toggle.cy.ts
- packages/player-component/cypress/component/multi-animation.cy.ts
- packages/player-component/cypress/component/player-controls.cy.ts
- packages/react-player/cypress/component/autoplay.cy.tsx
- packages/react-player/cypress/component/background.cy.tsx
- packages/react-player/cypress/component/get-versions.cy.tsx
- packages/react-player/cypress/component/hover.cy.tsx
- packages/react-player/cypress/component/interactivity/enable-interactivity.cy.tsx
- packages/react-player/cypress/component/interactivity/exploding-pigeon.cy.tsx
- packages/react-player/cypress/component/interactivity/state-toggle.cy.tsx
- packages/react-player/cypress/component/intermission.cy.tsx
- packages/react-player/cypress/component/loop.cy.tsx
- packages/react-player/cypress/component/mode.cy.tsx
- packages/react-player/cypress/component/multi-animation.cy.tsx
- packages/react-player/cypress/component/player-controls.cy.tsx
> fix: moved tests to force click

- packages/player-component/tsup.config.js
> chore: 🤖 backward compatible player-component build

- .changeset/cyan-pigs-move.md
- packages/player-component/tsup.config.js
> fix: 🐛 broken UMD with code splitting

- .changeset/quiet-carrots-count.md
> chore: changeset to bump players

- apps/dotlottie-playground/src/components/file-tree/index.tsx
- apps/dotlottie-playground/src/components/player.tsx
- apps/dotlottie-playground/src/components/playground.tsx
> fix: 🐛 fixed playground issues

- .changeset/hungry-ears-hear.md
- packages/common/src/dotlottie-player.ts
Fixes: https://lottiefiles.slack.com/archives/C01BNHRG5A6/p1694750894791529
> fix: 🐛 added default filterSize, fixes the drop shadows

- .changeset/orange-dots-teach.md
- packages/react-player/src/react-player.tsx
> fix: 🐛 cleanup for eventListeners

- .changeset/new-pumas-knock.md
- packages/common/src/dotlottie-player.ts
> fix: 🐛 error removing eventListeners when unmount

- .changeset/weak-grapes-smoke.md
- packages/react-player/package.json
- packages/react-player/src/hooks/index.ts
- packages/react-player/src/index.ts
- pnpm-lock.yaml
> fix: 🐛 react-player types build issue

- .changeset/serious-tables-glow.md
- packages/react-player/package.json
- pnpm-lock.yaml
> fix: 🐛 react-player couldn't find package "@dotlottie/common"

- .changeset/config.json
- .changeset/thirty-bees-move.md
> chore: 🤖 add changesets for @dotlottie/common

- .changeset/config.json
> chore: 🤖 update changesets config

- .changeset/fifty-toes-push.md
- .size-limit.cjs
- packages/common/tsup.config.js
- packages/player-component/tsup.config.js
- packages/react-player/tsup.config.js
> fix: 🐛 target build for chrome79

- .changeset/hot-ties-behave.md
- packages/common/package.json
- pnpm-lock.yaml
> chore: 🤖 update dependencies

- packages/common/src/dotlottie-player.ts
- packages/common/src/utils.ts
> fix: 🐛 deepClone to prevent lottie-web mutating lottie json obj

- .changeset/tall-horses-train.md
- .github/workflows/main.yml
> chore: 🤖 update changeset

- .changeset/violet-ravens-draw.md
> chore: 🤖 add missing changeset

- .changeset/hot-boxes-poke.md
- package.json
- packages/player-component/package.json
- packages/react-player/package.json
> chore: 🤖 fix homepage link in package.json
